[project]
name = "Ostat hose and pipe adapter"
uri = "https://github.com/ostat/vacuum-hose-adapter-openscad"
export-filename-prefix = "hose"
mode = "multi"
head-extra = ''

[model-template.default]
description-extra-html = "<br><br>For detailed documentation, check the <a href='https://github.com/ostat/gridfinity_extended_openscad'>README</a>.<br><br>"

[model-template.section-connector-1]
help-link = "https://docs.ostat.com/docs/openscad/hose-adapter/connectors"
collapsed = false

[model-template.section-connector-1---hose-connector]
help-link = "https://docs.ostat.com/docs/openscad/hose-adapter/connectors/hose"
collapsed = true

[model-template.section-connector-1---flange]
help-link = "https://docs.ostat.com/docs/openscad/hose-adapter/connectors/flange"
collapsed = true

[model-template.section-connector-1---magnetic-connector]
help-link = "https://docs.ostat.com/docs/openscad/hose-adapter/connectors/magnetic"
collapsed = true

[model-template.section-connector-1---extension]
help-link = "https://docs.ostat.com/docs/openscad/hose-adapter/transition/extension"
collapsed = true

[model-template.section-transition]
help-link = "https://docs.ostat.com/docs/openscad/hose-adapter/transition/configuration"
collapsed = false

[model-template.section-transition-multiple-connector-settings]
help-link = "https://docs.ostat.com/docs/openscad/hose-adapter/transition/multiple-connector"
collapsed = true

[model-template.section-transition-support-for-angled-pipes]
help-link = "https://docs.ostat.com/docs/openscad/hose-adapter/transition/angled-support"
collapsed = true

[model-template.section-connector-2]
help-link = "https://docs.ostat.com/docs/openscad/hose-adapter/connectors"
collapsed = false

[model-template.section-connector-2---hose-connector]
help-link = "https://docs.ostat.com/docs/openscad/hose-adapter/connectors/hose"
collapsed = true

[model-template.section-connector-2---flange]
help-link = "https://docs.ostat.com/docs/openscad/hose-adapter/connectors/flange"
collapsed = true

[model-template.section-connector-2---magnetic-connector]
help-link = "https://docs.ostat.com/docs/openscad/hose-adapter/connectors/magnetic"
collapsed = true

[model-template.section-connector-2---nozzle]
help-link = "https://docs.ostat.com/docs/openscad/hose-adapter/connectors/nozzle"
collapsed = true

[model-template.section-connector-2---extension]
help-link = "https://docs.ostat.com/docs/openscad/hose-adapter/transition/extension"
collapsed = true

[model-template.section-connector-3]
help-link = "https://docs.ostat.com/docs/openscad/hose-adapter/connectors"
collapsed = false

[model-template.section-connector-3---hose-connector]
help-link = "https://docs.ostat.com/docs/openscad/hose-adapter/connectors/hose"
collapsed = true

[model-template.section-connector-3---flange]
help-link = "https://docs.ostat.com/docs/openscad/hose-adapter/connectors/flange"
collapsed = true

[model-template.section-connector-3---magnetic-connector]
help-link = "https://docs.ostat.com/docs/openscad/hose-adapter/connectors/magnetic"
collapsed = true

[model-template.section-connector-3---nozzle]
help-link = "https://docs.ostat.com/docs/openscad/hose-adapter/connectors/nozzle"
collapsed = true

[model-template.section-connector-3---extension]
help-link = "https://docs.ostat.com/docs/openscad/hose-adapter/transition/extension"
collapsed = true

[[model]]
file = "vacuum-hose-adapter-basic.scad"
template = [
    "section-connector-1",
    "section-connector-1---hose-connector",
    "section-transition",
    "section-connector-2",
    "section-connector-2---hose-connector",
    ]

[[model]]
file = "vacuum-hose-adapter.scad"
template = [
    "section-connector-1",
    "section-connector-1---hose-connector",
    "section-connector-1---flange",
    "section-connector-1---magnetic-connector",
    "section-connector-1---extension",
    "section-transition",
    "section-transition-multiple-connector-settings",
    "section-transition-support-for-angled-pipes",
    "section-connector-2",
    "section-connector-2---hose-connector",
    "section-connector-2---flange",
    "section-connector-2---magnetic-connector",
    "section-connector-2---nozzle",
    "section-connector-2---extension",
    "section-connector-3",
    "section-connector-3---hose-connector",
    "section-connector-3---flange",
    "section-connector-3---magnetic-connector",
    "section-connector-3---nozzle",
    "section-connector-3---extension"
    ]

[[model]]
file = "funnels.scad"